### ISSUE TITLE
Can't create subsequent issues without restarting

### ISSUE THREAD

**Issue by heaths** [AlexGhiondea/IssueCreator#6]
This used to work, but no longer does. I create an issue, change the repo and epic, click *Create issue* again, and get this exception:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at IssueCreator.IssueManager.<TryCreateNewIssueAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IssueCreator.frmMain.<BtnCreateIssue_Click>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
IssueCreator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/IssueCreator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Text.Json
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Text.Json.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.27617.02
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.ValueTuple.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Text.Encodings.Web.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Numerics.Vectors.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Buffers.DLL
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 3.1.2.0
    Win32 Version: 3.100.220.6706
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Extensions.Caching.Memory.DLL
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 3.1.2.0
    Win32 Version: 3.100.220.6706
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Extensions.Options.DLL
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 3.1.2.0
    Win32 Version: 3.100.220.6706
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Extensions.Caching.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 3.1.2.0
    Win32 Version: 3.100.220.6706
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 3.1.2.0
    Win32 Version: 3.100.220.6706
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Extensions.Primitives.DLL
----------------------------------------
Octokit
    Assembly Version: 0.36.0.0
    Win32 Version: 0.36.0.0
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Octokit.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
ZenHub
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/ZenHub.DLL
----------------------------------------
Azure.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.19.52904
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Azure.Core.DLL
----------------------------------------
System.Threading.Tasks.Extensions
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.27129.04
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Threading.Tasks.Extensions.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Microsoft.Bcl.AsyncInterfaces
    Assembly Version: 1.0.0.0
    Win32 Version: 4.700.19.46214
    CodeBase: file:///C:/Users/heaths/AppData/Local/Apps/2.0/CGOEMKTT.3PN/WVP6KAJO.WGV/issu..tion_0000000000000000_0001.0000_296979ae4aee220c/Microsoft.Bcl.AsyncInterfaces.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Previously, I was also getting a server-side validation error that resulted in the same experience. This stack trace appeared only after restarting the app. With PATs, I can't imagine anything went stale.

No time to look at this now with a workaround (restart the app) available.

**Comment by AlexGhiondea** [comment]
I'm looking into this

**Comment by AlexGhiondea** [comment]
I found the problem -- a missing null check (of course). I will fix that and make another small improvement and push a PR.
